### ISSUE TITLE
Greeting Bot

### ISSUE THREAD

**Issue by muthuannamalai12** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#101]
Create a Contributor Greetings Bot.
Every Contributor to an OpenSource Project is special that is why I feel We should add a small GithubAction to give a warm welcome to the contributors.

**Comment by muthuannamalai12** [comment]
I would love to work on this issue as a part of Girl Script Summer Of Code. Kindly assign it to me.

**Comment by PetalsOnWind** [comment]
I don't think its necessary at this stage
