### ISSUE TITLE
Notebook on Pandas Library

### ISSUE THREAD

**Issue by Dishita2602** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#102]
Heyy, I would be completely explaining pandas library from scratch eg - how to create data frame, read and write in csv file etc. Code with explanation plus theory. So kindly assign me (GSSoc'21 Participant)

**Comment by Elizah550** [comment]
HEYY!!
I  have already done this notebook similarily in my initial learning  process you can assign it to me. Thanks!!

**Comment by PetalsOnWind** [comment]
I don't think this notebook constitutes an essential part of this project so I am closing this issue for now.
