### ISSUE TITLE
Notebook on precision and recall

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#11]
Should include case studies and what happens with precision and recall is high/low.

**Comment by prit108** [comment]
Hey @PetalsOnWind I would like to work on this... Can you clarify by case studies does it mean I should code full fledged models from datasets ?

**Comment by PetalsOnWind** [comment]
@prit108 Yes. The datasets should be existing datasets and not random simulated numbers

**Comment by prit108** [comment]
@PetalsOnWind should I do a section on ROC curves, AUC as well?

**Comment by prit108** [comment]
@PetalsOnWind  i have created a new pull request. Please review the document and suggest any changes if required.
I already see an issue for ROC/AUC, therefore I didn't add it .
