### ISSUE TITLE
Fix Documentation in notebooks/Central Limit Theorem.ipynb

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#111]
Fixes required:

1. Add more comments in the code cells
2. Add the mathematical formulations for central limit theorem

**Comment by Ayushisood** [comment]
Hii @PetalsOnWind I would like to work on this issue as a GSSOC'21 participant
Looking forward for the positive response

**Comment by harleenkaur76** [comment]
@PetalsOnWind i am a gssoc participant and would love to work on this issue

**Comment by jaimehta1912** [comment]
@rishabh-me Kindly Assign me this issue .I am gssoc 2021 participant.I will make sure to make a PR by tommorow morning .I am Partially done with the coding part

**Comment by jaimehta1912** [comment]
@PetalsOnWind  please assign me this issue

**Comment by KHUSHI-SANGAL** [comment]
I am also a gssoc'21 participant and want to work on your project.

**Comment by jaimehta1912** [comment]
@KHUSHI-SANGAL I am done with the coding part .I will make a PR by today

**Comment by KHUSHI-SANGAL** [comment]
That's great @jaimehta1912. I will work on some other issue.
