### ISSUE TITLE
Notebook on Exploratory Data Analysis

### ISSUE THREAD

**Issue by aakriti1318** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#126]
Hey @PetalsOnWind, Gssoc21 participant 
EDA is a technique to analyze data and it uses statistical analysis and graphical presentation to extract main characteristics and features.
I would like to work on this issue.

**Comment by Simar05519** [comment]
Hey, please assign me this issue. I would like to work by giving statistical approach

**Comment by PetalsOnWind** [comment]
Received too many issues on this already
