### ISSUE TITLE
Add gitignore file for ipynb_checkpoints

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#13]
Trivial issue meant to give an easy accomplishment. Will not count towards final evaluation

**Comment by basilisk-2001** [comment]
@PetalsOnWind  I'm interested to contribute my ideas on this topic and work on the same , but please give me a detailed explanation on the work that I need to do , as I'm new to open source .

**Comment by PetalsOnWind** [comment]
@basilisk-2001 This is a very easy issue. Just search what a .gitignore file is.

All you have to do is to fork this repo, make a clone on your local system (follow any git tutorial for that). After that, make a folder named `.gitignore` and add the following lines to it:
```.ipynb_checkpoints/
notebooks/.ipynb_checkpoints/```
Then push it to your fork and send a PR (again any git tutorial will tell you how)

**Comment by mridul2899** [comment]
> @basilisk-2001 This is a very easy issue. Just search what a .gitignore file is.
> 
> All you have to do is to fork this repo, make a clone on your local system (follow any git tutorial for that). After that, make a folder named `.gitignore` and add the following lines to it:
> 
> ```
> .ipynb_checkpoints/
> notebooks/.ipynb_checkpoints/
> ```
> 
> Then push it to your fork and send a PR (again any git tutorial will tell you how)

As far as I'm aware, if we add .gitignore in the top level, the files/folders in the subdirectories are ignored by default. So merely adding `.ipynb_checkpoints/` should suffice.

**Comment by PetalsOnWind** [comment]
@mridul2899 Thanks for the tip! I was unsure of that so I thought of adding both to be sure
