### ISSUE TITLE
Readme file enhancement

### ISSUE THREAD

**Issue by anirudhsai20** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#146]
The Readme file can be enhanced by adding a list of all the Open Source programs in which this project has been listed in. Also there are a few minor grammatical errors that needs correction.

**Comment by anirudhsai20** [comment]
Hi! Please assign this issue to me under GSSOC.

**Comment by AnushkaThakkar** [comment]
Hey @anirudhsai20 ,
This is an open issue, you can create a PR

**Comment by anirudhsai20** [comment]
Hi. Please assign this issue to me so that I can proceed with my PR.

**Comment by anirudhsai20** [comment]
Hi! Please check my pull request.

**Comment by anirudhsai20** [comment]
Please check Pr #157.

**Comment by anirudhsai20** [comment]
Hi! Please check my PR.
