### ISSUE TITLE
New Notebook for Random Forest Algorithm (for Regression and Classification)

### ISSUE THREAD

**Issue by ashwinraj-in** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#158]
Hi @PetalsOnWind, I wish to implement the **Random forest algorithm** for both _Regression and Classification_ problems and also include the mathematics behind it. I have previously written a detailed blog explaining the entire algorithm for solving  regression problems.

Checkout the blog here: https://towardsdatascience.com/a-quick-and-dirty-guide-to-random-forest-regression-52ca0af157f8

 So can you please assign me this?

**Comment by PetalsOnWind** [comment]
No ML issues will be assigned
