### ISSUE TITLE
Modifying/Styling Readme.md file

### ISSUE THREAD

**Issue by DOOMSTERR** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#162]
# Proposed Changes
### Modifying by adding 

1.)Adding emojis and changing alignments of some 
headings/text to make it look better.

2.)Adding Sections:
->In Contributor Section adding
>Project Manager/Admin Section

3.) To remove the table of content section as it is a feature already given by Github. (optional only if permitted by admin)

Hello, @PetalsOnWind, Please assign me this issue under the GSSOC21 label and Levels label.

Thank You.

**Comment by aryasoni98** [comment]
I would like to work on it . Assign me @DOOMSTERR

**Comment by PetalsOnWind** [comment]
Looks like stock issue and not interested in those.
