### ISSUE TITLE
Add detailed explanation and comments in data_summary_breast_cancer.ipynb

### ISSUE THREAD

**Issue by mehak6569** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#164]
I want to add detailed explanation through comments and markdowns in the [data_summary_breast_cancer.ipynb](https://github.com/PetalsOnWind/Statistics-and-Econometrics-for-Data-Science/blob/main/notebooks/data_summary_breast_cancer.ipynb) file, so that even a ML beginner can read and understand the notebook easily. 
Please assign this issue to me.

**Comment by PetalsOnWind** [comment]
I think other issues should be handled first before this is fleshed out more
