### ISSUE TITLE
Adding comments and explanation to the given code in intro-numpy-pandas-matplotlib.ipynb

### ISSUE THREAD

**Issue by Tejal18** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#165]
I want to add comments and a detailed explanation to intro-numpy-pandas-matplotlib.ipynb notebook . 
By adding comments and explanation the code will be easily understood by a beginner. 
Please do assign me this issue.
Thanks.

**Comment by PetalsOnWind** [comment]
Not important right now. That notebook will be deleted in near future
