### ISSUE TITLE
Notebook on joint probability distributions

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#19]

**Comment by JanhaviSoni** [comment]
Can you please give the details about the topic and how do we need to proceed for its implementation and things to be done under this topic?

**Comment by PetalsOnWind** [comment]
@JanhaviSoni I expect a notebook that details what joint probability distributions are, some graphs, information on marginal and conditional probabilities (You can easily find resources to understand with a Google search)

**Comment by JanhaviSoni** [comment]
Please assign me this topic and guide me like how should I proceed. Should I start like this : making a separate notebook on this topic and adding definitions and examples and making first PR then adding more info graphs . Please guide me like how should I proceed. I am new to open source.

**Comment by PetalsOnWind** [comment]
Yes, you can start like you said.

**Comment by abhishek5601** [comment]
Hi @PetalsOnWind, I would also like to work on this issue. Would it be fine if I can work with @JanhaviSoni and coordinate with her?

**Comment by JanhaviSoni** [comment]
@PetalsOnWind Please have a review if the branch is ready to get merged.

**Comment by PetalsOnWind** [comment]
@JanhaviSoni Some minor fixes needed but otherwise looks good
