### ISSUE TITLE
Notebook on maximum likelihood estimation

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#20]

**Comment by mridul2899** [comment]
I want to work on this issue. From what I understand, the notebook must describe the need for maximum likelihood estimation, the mathematics involved along with the derivations, working codes from scratch, and some applications. For now, I plan to do this for the elementary probability distributions like the Bernoulli, binomial, exponential, Poisson, normal distributions, and then I can extend it to other distributions as well.
I would be glad to know what more I should aim for.

**Comment by PetalsOnWind** [comment]
@mridul2899 Sounds good to me. I had plan for normal distribution only but other distributions also sound good
