### ISSUE TITLE
Notebook on ANOVA

### ISSUE THREAD

**Issue by PetalsOnWind** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#26]

**Comment by PriyaJ28** [comment]
Can you please give the details about the topic and a brief about how to proceed for implementation and things to be done under this topic?

**Comment by PetalsOnWind** [comment]
ANOVA stands for Analysis of Variance. What I expect are details on how to conduct ANOVA and some functions to test the hypotheses for ANOVA. 
Reference: Chapter 2 Simple Comparative Experiments from Design and Analysis of Experiments by Montogomery

**Comment by skkarn21** [comment]
I am interested in this.
