### ISSUE TITLE
Matplotlib - Data visualisation library

### ISSUE THREAD

**Issue by pawan-git7979** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#73]
I would like to add various plots to this notebook, that's comes under the mathplotlib, and how can be made them for interseting , readable and can gain more insights from them.
would like to work on this issue[GSSOC 21].

**Comment by nNikita1018** [comment]
I want to work with this issue ..
In  python language

**Comment by Pavithra2206** [comment]
Hey @PetalsOnWind , I am GSSOC'21 participant ,can u assign me this issue ? I have significant exposure in data science (you can see my work in my repos)

**Comment by PragatiBhat** [comment]
@PetalsOnWind I am GSSOC'21 participant ,can u assign me this issue ?

**Comment by Anam118** [comment]
I am a participant in GSSOC 2021 and want to work on this issue.

**Comment by harshita-d** [comment]
hi I am Harshita, I would like to contribute to this as a part of GSSOC Participant 2021. please assign me as i have used on matplotlib library before.

**Comment by Dishita2602** [comment]
Hello, I am an GSSOC'21 participant and want to address this issue. I can do exploratory data analysis by using Numpy, Pandas, Seaborn, Matplotlib and additionally use Sweetviz library. Also my code would be clean and easy to understand. I am ready to use some other libraries for better visualization.

**Comment by PetalsOnWind** [comment]
@pawan-git7979  since you proposed this issue, can you explain more? This project is more towards concepts (statistical, econometrics) than use of a library. Can you propose more additions to make it more relevant?

**Comment by harleenkaur76** [comment]
i am a gssoc participant and i would love to work on this . i will be explaining this with relevant matter and examples.

**Comment by pawan-git7979** [comment]
> @pawan-git7979  since you proposed this issue, can you explain more? This project is more towards concepts (statistical, econometrics) than use of a library. Can you propose more additions to make it more relevant?

Okk, sorry for the inconvenience.
I thought graphs are the best way to draw insight from the data and to do EDA, so i proposed a matplotlib issue.

**Comment by Simar05519** [comment]
I want to work on this issue. Please assign to me.

**Comment by Elizah550** [comment]
Hey!!
I can work on this I have the best idea to put this in a best place so please assign it to me I would do it in the best possible way.
Thanks !!
