### ISSUE TITLE
Notebook on Decision Tree 

### ISSUE THREAD

**Issue by Dhanush2612** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#77]
Notebook on Decision Tree by making use of Titanic Survival Prediction as sample.

**Comment by Dhanush2612** [comment]
Kindly assign me this issue

**Comment by PetalsOnWind** [comment]
@Dhanush2612 I would prefer if logit and probit regressions were covered first. Also, I am not concerned about any particular dataset and this issue doesn't seem relevant to this project unless you propose more additions (from either mathematical, statistical or econometrics point of view)
