### ISSUE TITLE
add contributing.md

### ISSUE THREAD

**Issue by khareyash05** [PetalsOnWind/Statistics-and-Econometrics-for-Data-Science#79]
Hey! I would like to add the following in contributing.md
Add the following -

1.Difference between GIT and GITHUB
2.How to clone,fork repository
3.How to create a branch and then use git push to push to repo
4.Create a PR
5.Squash commits in a single issue into one
6, Updating the forked and local repo as the updations are made in the upstream
I would like to work on this as a part of GSSOC'21

**Comment by PetalsOnWind** [comment]
@khareyash05 This project is more about concepts (mathematical, statistical and econometrics) in a DS context rather than use of any particular tech. You would have to do some more additions before I would consider this issue as a part of GSSOC'21
